const palabras = {
    "El amor": "L'amore",
    "El niño": "Il bambino",
    "La casa": "La casa",
    "El mañana": "Il domani",
    "El elefante": "L'elefante",
    "La familia": "La famiglia",
    "El gato": "Il gatto",
    "El hotel": "L'hotel",
    "La isla": "L'isola",
    "Los jeans": "I jeans",
    "El kilo":"Il kilo",
    "El libro":"Il libro",
    "La mamá": "La mamma",
    "La noche": "La notte",
    "El paraguas": "L'ombrello",
    "El papa": "Il papa",
    "El cuadro": "Il cuadro",
    "La rosa": "La rosa",
    "El sol": "Il sole",
    "La mesa": "Il tavolo",
    "El hombre": "L'uomo",
    "El vino": "Il vino",
    "El warerloo": "Il waterloo",
    "El xilofóno": "Il Xilofono",
    "El yoga": "Lo yoga",
    "El azúcar":"Lo zuccero"}

